# Generated by Django 5.1.3 on 2026-03-30 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="contact_docs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "doc", "docx", "txt"]
                    )
                ],
            ),
        ),
    ]
